sonar.organization=gpi-sonar
sonar.projectKey=gpi-app-sonar
sonar.projectName=GPI-App
sonar.projectVersion=0.0.1

sonar.sources=innovo-app
sonar.exclusions=innovo-app/node_modules/**,innovo-app/assets/**

# Tests configuration
# sonar.tests=tests
# sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.typescript.tsconfigPath=innovo-app/tsconfig.json
